language: python
python:
  - "2.7"
install:
  - "MY_VIRTUAL_ENV=$VIRTUAL_ENV"
  - "deactivate"
  - "virtualenv --clear --python /usr/bin/python $MY_VIRTUAL_ENV"
  - "source $MY_VIRTUAL_ENV/bin/activate"
  - "pip install pytest nose mock"
  - "python ez_setup.py"
  - "pip install -r requirements.txt --find-links http://cheshire3.liv.ac.uk/download/latest/reqs/ --allow-unverified PyZ3950 --allow-unverified ZSI"
  - "python setup.py install"
# Run tests for Cheshire3 and archiveshub
script:
  - python -m cheshire3.test.testAll
  - python setup.py test
