language: python
python:
  - "2.7"
# Install dependencies
install:
  - "python ez_setup.py"
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py install"
# Run tests
script: python setup.py test

