language: python
python:
  - "2.7"
virtualenv:
  # Base virtualenv on Ubuntu package Python for bsddb dependency
  - python: /usr/bin/python
install:
  - "python ez_setup.py"
  - "pip install -r requirements.txt --find-links http://download.cheshire3.org/latest/reqs/ --allow-unverified PyZ3950 --allow-unverified ZSI"
  - "python setup.py install"
# Run tests
script: python setup.py test

